# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d3d0016d8e16512169eab7de8118e321"
name = "SafeServe - Allergen Labels"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
